services:
  iot_simulators:
    # Build the Docker image from the ./IoT_Hub directory
    build:
      context: ./IoT_Hub
      dockerfile: Dockerfile

    # Assign a fixed name to the container instance
    container_name: iot-simulators

    # Environment variables passed into the container at runtime
    environment:
    #  - LOG_LEVEL=DEBUG
    #  - SLACK_WEBHOOK_URL=https://hooks.slack.com/services/…

    # Always restart the container on failure or exit
    restart: Always
